var context = {
    "body": [
        {
            "city": "Waterloo",
            "races": [
                {
                    "race": "Mayor",
                    "candidates": [
                        {
                            "candidate": "Buck Clark",
                            "race": "Mayor",
                            "votes": "4601",
                            "totalvotes": "9115",
                            "votepercent": "50.48",
                            "precinctsreported": "31",
                            "precincts": "31",
                            "age": "64",
                            "education": "Mountain Home, Ark., High School graduate and two years at the University of Arkansas.",
                            "employment": "Current mayor; former small business owner and Waterloo police officer",
                            "community": "President of the Iowa League of Cities; Ward 3 City Councilman, 2002-05.",
                            "running": "\"Waterloo is experiencing unprecedented growth and opportunity, and I believe my leadership and attitude are contributing greatly to that. I want to continue our progress and prosperity for the next two years.\"",
                            "fun": "\"I love vegetables.\"",
                            "mug": "images/wloo/clark.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/waterloo-mayor-buck-clar…ets-sights-on-third-term/article_e85a9baa-ca0e-11e2-8cef-0019bb2963f4.html",
                            "raceentryhead": "\"Waterloo Mayor Buck Clark sets sights on third term\" (5/31/2013)\n",
                            "quote": "\"Waterloo is experiencing unprecedented growth and opportunity, and I believe my leadership and attitude are contributing greatly to that.\"",
                            "quotedate": "10/24/2013",
                            "quotelink": "",
                            "linkonehead": "\"Clark keeps mayor's seat with another narrow win over Schmitt\" (11/5/2013)",
                            "linkone": "http://wcfcourier.com/news/local/govt-and-politics/buck-clark-keeps-mayor-s…-with-another-narrow-win/article_a7bde1f3-e1fc-5eca-84d4-452b4ae1905c.html",
                            "linktwohead": "\"New faces, hot races highlight Waterloo city races\" (11/3/13)",
                            "linktwo": "http://wcfcourier.com/news/local/govt-and-politics/new-faces-hot-races-highlight-waterloo-city-races/article_d614a742-c6e5-5000-ba9e-32b1c63b7e61.html",
                            "linkthreehead": "\"Clark leads Schmitt in campaign cash\" (11/3/2013)",
                            "linkthree": "http://wcfcourier.com/news/local/govt-and-politics/clark-leads-schmitt-in-campaign-cash/article_ac1dd814-bb8a-5ad0-abba-65e0c6e7f6b7.html",
                            "linkfourhead": "\"Budget philosophy separates Waterloo mayoral hopefuls\" (10/27/2013)",
                            "linkfour": "http://wcfcourier.com/news/local/govt-and-politics/budget-philosophy-separa…aterloo-mayoral-hopefuls/article_a1b28fd5-77f0-548f-bc32-2a3ff475c635.html",
                            "linkfivehead": "\"Waterloo mayoral debate turns testy over taxes\" (10/18/2013)",
                            "linkfive": "http://wcfcourier.com/news/local/govt-and-politics/waterloo-mayoral-debate-turns-testy-over-taxes/article_dbb188ce-ef98-5ddc-84db-3cb4d564d8b8.html",
                            "linksixhead": "\"Ballot set for Waterloo elections\" (9/20/2013)",
                            "linksix": "http://wcfcourier.com/news/local/govt-and-politics/ballot-set-for-waterloo-elections/article_983bd17b-f42e-5e0f-ab98-c049050ac069.html",
                            "linksevenhead": "",
                            "linkseven": "",
                            "versus": "TRUE",
                            "rowNumber": 1,
                            "$index": 0,
                            "$first": true,
                            "$last": false
                        },
                        {
                            "candidate": "Steve Schmitt",
                            "race": "Mayor",
                            "votes": "4514",
                            "totalvotes": "9115",
                            "votepercent": "49.52",
                            "precinctsreported": "31",
                            "precincts": "31",
                            "age": "64",
                            "education": "BA in business management, University of Northern Iowa; AA in business marketing, Ellsworth Community College; Oelwein High School.",
                            "employment": "President of Schmitt Telecom Partners, Inc.",
                            "community": "Currently Board President of Boy Scouts, Greater Cedar Valley Alliance Ambassadors, Birthright of Black Hawk County; past president of Waterloo Jaycess, Waterloo Downtown Rotary, WCF Symphony; past board member Sacred Heart Catholic Church, Boys and Girls Club; active member of Big Brothers and Teammates mentoring in the Waterloo Schools, Knights of Columbus and Waterloo Elks.",
                            "running": "\"I think things have been trending well in Waterloo over the last 10 years, but I think we can and must do better and be more aggressive with our economic development. I believe my experience in the business world is just what the city needs to get us back to being one of the top cities in Iowa. I want my kids and grandkids to have opportunities and reasons to stay in Waterloo.\"",
                            "fun": "\"Since our triplets left home for college four years ago, my wife and I have had an ongoing ping pong tournament three or four nights a week. So far, I am losing.\"",
                            "mug": "images/wloo/schmitt.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/councilman-steve-schmitt…s-bid-for-waterloo-mayor/article_b10db4c6-f5ff-5622-9253-93f9d1ad2dae.html",
                            "raceentryhead": "\"Councilman Steve Schmitt announces bid for Waterloo mayor\" (9/17/2013)",
                            "quote": "\"I would put my track record, my business record, my success record, my financial success record up against (Buck Clark) any day of the week.\"",
                            "quotedate": "10/18/2013",
                            "quotelink": "http://wcfcourier.com/news/local/govt-and-politics/waterloo-mayoral-debate-turns-testy-over-taxes/article_dbb188ce-ef98-5ddc-84db-3cb4d564d8b8.html",
                            "linkonehead": "\"Clark keeps mayor's seat with another narrow win over Schmitt\" (11/5/2013)",
                            "linkone": "http://wcfcourier.com/news/local/govt-and-politics/buck-clark-keeps-mayor-s…-with-another-narrow-win/article_a7bde1f3-e1fc-5eca-84d4-452b4ae1905c.html",
                            "linktwohead": "\"New faces, hot races highlight Waterloo city races\" (11/3/13)",
                            "linktwo": "http://wcfcourier.com/news/local/govt-and-politics/new-faces-hot-races-highlight-waterloo-city-races/article_d614a742-c6e5-5000-ba9e-32b1c63b7e61.html",
                            "linkthreehead": "\"Clark leads Schmitt in campaign cash\" (11/3/2013)",
                            "linkthree": "http://wcfcourier.com/news/local/govt-and-politics/clark-leads-schmitt-in-campaign-cash/article_ac1dd814-bb8a-5ad0-abba-65e0c6e7f6b7.html",
                            "linkfourhead": "\"Waterloo city candidates face off at KBBG forum\" (11/3/2013)",
                            "linkfour": "http://wcfcourier.com/news/local/govt-and-politics/waterloo-city-candidates-face-off-at-kbbg-forum/article_cd26c02f-35db-5cc9-8db3-67fe5b09f416.html",
                            "linkfivehead": "\"Budget philosophy separates Waterloo mayoral hopefuls\" (10/27/2013)",
                            "linkfive": "http://wcfcourier.com/news/local/govt-and-politics/budget-philosophy-separa…aterloo-mayoral-hopefuls/article_a1b28fd5-77f0-548f-bc32-2a3ff475c635.html",
                            "linksixhead": "\"Waterloo mayoral debate turns testy over taxes\" (10/18/2013)",
                            "linksix": "http://wcfcourier.com/news/local/govt-and-politics/waterloo-mayoral-debate-turns-testy-over-taxes/article_dbb188ce-ef98-5ddc-84db-3cb4d564d8b8.html",
                            "linksevenhead": "\"Ballot set for Waterloo elections\" (9/20/2013)",
                            "linkseven": "http://wcfcourier.com/news/local/govt-and-politics/ballot-set-for-waterloo-elections/article_983bd17b-f42e-5e0f-ab98-c049050ac069.html",
                            "versus": "TRUE",
                            "rowNumber": 2,
                            "$index": 1,
                            "$first": false,
                            "$last": true
                        }
                    ]
                },
                {
                    "race": "Ward 3",
                    "candidates": [
                        {
                            "candidate": "Pat Morrissey",
                            "race": "Ward 3",
                            "votes": "892",
                            "totalvotes": "1491",
                            "votepercent": "59.83",
                            "precinctsreported": "7",
                            "precincts": "7",
                            "age": "64",
                            "education": "Waterloo Columbus High School; University of Northern Iowa, B.A. in sociology.",
                            "employment": "Retired state child/dependent adult abuse investigator; former alcohol/drug counselor",
                            "community": "Iowa Citizens for Community Improvement; Cedar Valley Bicycle Collective, board; Friends of the Gilbertville Depot, board; Cedar Valley Youth Soccer Association coach; Human Rights Coalition, past.",
                            "running": "\"To bring to the council a person who will meet with the ward’s people not only before the election, but also in regular face-to-face meetings after the election as their representative. To be a voice on the council that puts people first, puts the workers, the working poor, the underemployed, the unemployed and the disenfranchised first.\"",
                            "fun": "\"I am a student in learning the art of bagpipes (playing for Leprechauns).\"",
                            "mug": "images/wloo/morrissey.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/retired-state-investigat…rd-waterloo-council-seat/article_aa35f311-9147-5853-8806-c552eb8821d1.html",
                            "raceentryhead": "\"Retired state investigator runs for Ward 3 Waterloo council seat\" (9/30/2013)",
                            "quote": "\"I have grown up in the Church Row Neighborhood and raised my kids  there. I know the issues in Ward 3 and I want to make our neighborhoods better.\"",
                            "quotedate": "9/30/2013",
                            "quotelink": "http://wcfcourier.com/news/local/govt-and-politics/retired-state-investigat…rd-waterloo-council-seat/article_aa35f311-9147-5853-8806-c552eb8821d1.html",
                            "linkonehead": "\"Lind and Morrissey win Waterloo Council seats, Welper holds onto Ward 5\" (11/5/2013)\n",
                            "linkone": "http://wcfcourier.com/news/local/govt-and-politics/lind-and-morrissey-win-w…-seats-welper-holds-onto/article_f7911160-4c6e-5146-a5d9-cc1e306b93c3.html",
                            "linktwohead": "\"New faces, hot races highlight Waterloo city races\" (11/3/13)",
                            "linktwo": "http://wcfcourier.com/news/local/govt-and-politics/new-faces-hot-races-highlight-waterloo-city-races/article_d614a742-c6e5-5000-ba9e-32b1c63b7e61.html",
                            "linkthreehead": "\"Clark leads Schmitt in campaign cash\" (11/3/2013)",
                            "linkthree": "http://wcfcourier.com/news/local/govt-and-politics/clark-leads-schmitt-in-campaign-cash/article_ac1dd814-bb8a-5ad0-abba-65e0c6e7f6b7.html",
                            "linkfourhead": "\"Waterloo city candidates face off at KBBG forum\" (11/3/2013)",
                            "linkfour": "http://wcfcourier.com/news/local/govt-and-politics/waterloo-city-candidates-face-off-at-kbbg-forum/article_cd26c02f-35db-5cc9-8db3-67fe5b09f416.html",
                            "linkfivehead": "\"Four candidates battle for Waterloo Ward 3 Council post\" (10/29/2013)",
                            "linkfive": "http://wcfcourier.com/news/local/govt-and-politics/four-candidates-battle-f…terloo-ward-council-post/article_7e8bf78e-5fcb-59fe-8eb6-961fe2272380.html",
                            "linksixhead": "\"Waterloo City Council hopefuls introduce themselves at forum\" (10/18/2013)            ",
                            "linksix": "http://wcfcourier.com/news/local/govt-and-politics/waterloo-city-council-ho…duce-themselves-at-forum/article_52b1b80b-cccd-53e1-8976-018a463dd338.html",
                            "linksevenhead": "",
                            "linkseven": "",
                            "versus": "TRUE",
                            "rowNumber": 3,
                            "$index": 0,
                            "$first": true,
                            "$last": false
                        },
                        {
                            "candidate": "William Frost",
                            "race": "Ward 3",
                            "votes": "273",
                            "totalvotes": "1491",
                            "votepercent": "18.31",
                            "precinctsreported": "7",
                            "precincts": "7",
                            "age": "60",
                            "education": "Devry University, Chicago; John Deere's 8,000 hours, five-year apprenticeship program.",
                            "employment": "Technician at John Deere for 40 years, retiring in 2014; former Realtor; licensed insurance agent.",
                            "community": "Helped start the first Optimist Club in the Gateway area; helped start the Gateway Community Development Corp.; trustee at Antioch Baptist Church.",
                            "running": "\"I feel Waterloo need a strong independent leader, to stay focused and address the issue of developing the North 63 corridor, first by changing the perception of the North 63 corridor by giving it a strong, positive name of Gateway to the North and the surrounding area called Gateway Community. By staying focused and working with a farmer mentality in developing the Gateway Community we would increase our tax base, which would increase the revenue for the City of Waterloo, so we can support the necessary spending to maintain this city and work toward reducing the property taxes in Waterloo, which would make Waterloo more attractive.\"",
                            "fun": "\"I love riding a bike, staying active physically, playing chess and shooting pool. Also dressing nice, like they use to do here in Waterloo.\"",
                            "mug": "images/wloo/frost.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/ward-city-council-candid…st-focuses-on-north-side/article_07f02891-17a8-5ceb-b85a-88895cc954e9.html",
                            "raceentryhead": "\"Ward 3 City Council candidate William Frost focuses on north side development\" (10/2/2013)",
                            "quote": "\"I believe Waterloo needs a strong independent leader to address the issues of developing the north Waterloo, Highway 63 corridor.\"",
                            "quotedate": "10/2/2013",
                            "quotelink": "http://wcfcourier.com/news/local/govt-and-politics/dustin-cox-to-seek-ward-…terloo-city-council-seat/article_68456379-744f-547a-97b2-aaf0cd267568.html",
                            "linkonehead": "\"Lind and Morrissey win Waterloo Council seats, Welper holds onto Ward 5\" (11/5/2013)",
                            "linkone": "http://wcfcourier.com/news/local/govt-and-politics/lind-and-morrissey-win-w…-seats-welper-holds-onto/article_f7911160-4c6e-5146-a5d9-cc1e306b93c3.html",
                            "linktwohead": "\"New faces, hot races highlight Waterloo city races\" (11/3/13)",
                            "linktwo": "http://wcfcourier.com/news/local/govt-and-politics/new-faces-hot-races-highlight-waterloo-city-races/article_d614a742-c6e5-5000-ba9e-32b1c63b7e61.html",
                            "linkthreehead": "\"Clark leads Schmitt in campaign cash\" (11/3/2013)",
                            "linkthree": "http://wcfcourier.com/news/local/govt-and-politics/clark-leads-schmitt-in-campaign-cash/article_ac1dd814-bb8a-5ad0-abba-65e0c6e7f6b7.html",
                            "linkfourhead": "\"Four candidates battle for Waterloo Ward 3 Council post\" (10/29/2013)",
                            "linkfour": "http://wcfcourier.com/news/local/govt-and-politics/four-candidates-battle-f…terloo-ward-council-post/article_7e8bf78e-5fcb-59fe-8eb6-961fe2272380.html",
                            "linkfivehead": "\"Waterloo City Council hopefuls introduce themselves at forum\" (10/18/2013)            ",
                            "linkfive": "http://wcfcourier.com/news/local/govt-and-politics/waterloo-city-council-ho…duce-themselves-at-forum/article_52b1b80b-cccd-53e1-8976-018a463dd338.html",
                            "linksixhead": "",
                            "linksix": "",
                            "linksevenhead": "",
                            "linkseven": "",
                            "versus": "TRUE",
                            "rowNumber": 4,
                            "$index": 1,
                            "$first": false,
                            "$last": false
                        },
                        {
                            "candidate": "Dustin Cox",
                            "race": "Ward 3",
                            "votes": "245",
                            "totalvotes": "1491",
                            "votepercent": "16.43",
                            "precinctsreported": "7",
                            "precincts": "7",
                            "age": "32",
                            "education": "University of Northern Iowa, BA Teaching; MA Youth and Human Services Administration.",
                            "employment": "Teacher at George Washington Carver Academy",
                            "community": "Waterloo Human Rights Commission, vice chair; Waterloo Planning, Programming and Zoning Commission, vice chair.",
                            "running": "\"I will work to bring new economic development to the Highway 63 and Broadway corridor, enlarging our tax base and making these areas more aesthetically appealing. Waterloo's increasingly high taxes are unsustainable and crippling our growth effort. Public safety must be our first priority. We must do a better job of engaging the community in public safety discussions while communicating the many successes of our public safety departments.\"",
                            "fun": "\"I've been to 12 countries.\"",
                            "mug": "images/wloo/cox.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/dustin-cox-to-seek-ward-…terloo-city-council-seat/article_68456379-744f-547a-97b2-aaf0cd267568.html",
                            "raceentryhead": "\"Dustin Cox to seek Ward 3 Waterloo City Council seat\" (9/17/2013)",
                            "quote": "\"I am eagerly anticipating the day that Waterloo becomes the most business-friendly city in Iowa.\"",
                            "quotedate": "9/17/2013",
                            "quotelink": "http://wcfcourier.com/news/local/govt-and-politics/dustin-cox-to-seek-ward-…terloo-city-council-seat/article_68456379-744f-547a-97b2-aaf0cd267568.html",
                            "linkonehead": "\"Lind and Morrissey win Waterloo Council seats, Welper holds onto Ward 5\" (11/5/2013)",
                            "linkone": "http://wcfcourier.com/news/local/govt-and-politics/lind-and-morrissey-win-w…-seats-welper-holds-onto/article_f7911160-4c6e-5146-a5d9-cc1e306b93c3.html",
                            "linktwohead": "\"New faces, hot races highlight Waterloo city races\" (11/3/13)",
                            "linktwo": "http://wcfcourier.com/news/local/govt-and-politics/new-faces-hot-races-highlight-waterloo-city-races/article_d614a742-c6e5-5000-ba9e-32b1c63b7e61.html",
                            "linkthreehead": "\"Clark leads Schmitt in campaign cash\" (11/3/2013)",
                            "linkthree": "http://wcfcourier.com/news/local/govt-and-politics/clark-leads-schmitt-in-campaign-cash/article_ac1dd814-bb8a-5ad0-abba-65e0c6e7f6b7.html",
                            "linkfourhead": "\"Four candidates battle for Waterloo Ward 3 Council post\" (10/29/2013)",
                            "linkfour": "http://wcfcourier.com/news/local/govt-and-politics/four-candidates-battle-f…terloo-ward-council-post/article_7e8bf78e-5fcb-59fe-8eb6-961fe2272380.html",
                            "linkfivehead": "\"Waterloo City Council hopefuls introduce themselves at forum\" (10/18/2013)            ",
                            "linkfive": "http://wcfcourier.com/news/local/govt-and-politics/waterloo-city-council-ho…duce-themselves-at-forum/article_52b1b80b-cccd-53e1-8976-018a463dd338.html",
                            "linksixhead": "",
                            "linksix": "",
                            "linksevenhead": "",
                            "linkseven": "",
                            "versus": "TRUE",
                            "rowNumber": 5,
                            "$index": 2,
                            "$first": false,
                            "$last": false
                        },
                        {
                            "candidate": "Shane Blackledge",
                            "race": "Ward 3",
                            "votes": "81",
                            "totalvotes": "1491",
                            "votepercent": "5.43",
                            "precinctsreported": "7",
                            "precincts": "7",
                            "age": "34",
                            "education": "Hawkeye Community College, associates degree; University of Northern Iowa, currently working BA in education, minor business management.",
                            "employment": "Menards employee and owner of A Plus Carpentry",
                            "community": "Mentoring for Waterloo Schools.",
                            "running": "\"I'm running to bring cultural diversity and awareness to our local government. I'm running to organize the community and neighborhoods of Waterloo, bring everyone together to promote peace and safety on our streets. I'm running to promote the great things this city has to offer and to make this place a safer place for our children.\"",
                            "fun": "\"I'm Chinese American.\"",
                            "mug": "images/wloo/blackledge.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/shane-blackledge-joins-ward-waterloo-council-race/article_bae23d5b-e2a2-5e2f-8a17-9aaaade086b8.html",
                            "raceentryhead": "\"Shane Blackledge joins Ward 3 Waterloo Council race\" (9/20/2013)",
                            "quote": "\"I have a passion for a better, safer, cleaner environment — going green to LED lighting. We need to go forward with all of those things now and not put it on the back burner.\"",
                            "quotedate": "9/20/2013",
                            "quotelink": "http://wcfcourier.com/news/local/govt-and-politics/shane-blackledge-joins-ward-waterloo-council-race/article_bae23d5b-e2a2-5e2f-8a17-9aaaade086b8.html",
                            "linkonehead": "\"Lind and Morrissey win Waterloo Council seats, Welper holds onto Ward 5\" (11/5/2013)",
                            "linkone": "http://wcfcourier.com/news/local/govt-and-politics/lind-and-morrissey-win-w…-seats-welper-holds-onto/article_f7911160-4c6e-5146-a5d9-cc1e306b93c3.html",
                            "linktwohead": "\"New faces, hot races highlight Waterloo city races\" (11/3/13)",
                            "linktwo": "http://wcfcourier.com/news/local/govt-and-politics/new-faces-hot-races-highlight-waterloo-city-races/article_d614a742-c6e5-5000-ba9e-32b1c63b7e61.html",
                            "linkthreehead": "\"Clark leads Schmitt in campaign cash\" (11/3/2013)",
                            "linkthree": "http://wcfcourier.com/news/local/govt-and-politics/clark-leads-schmitt-in-campaign-cash/article_ac1dd814-bb8a-5ad0-abba-65e0c6e7f6b7.html",
                            "linkfourhead": "\"Four candidates battle for Waterloo Ward 3 Council post\" (10/29/2013)",
                            "linkfour": "http://wcfcourier.com/news/local/govt-and-politics/four-candidates-battle-f…terloo-ward-council-post/article_7e8bf78e-5fcb-59fe-8eb6-961fe2272380.html",
                            "linkfivehead": "\"Waterloo City Council hopefuls introduce themselves at forum\" (10/18/2013)            ",
                            "linkfive": "http://wcfcourier.com/news/local/govt-and-politics/waterloo-city-council-ho…duce-themselves-at-forum/article_52b1b80b-cccd-53e1-8976-018a463dd338.html",
                            "linksixhead": "",
                            "linksix": "",
                            "linksevenhead": "",
                            "linkseven": "",
                            "versus": "TRUE",
                            "rowNumber": 6,
                            "$index": 3,
                            "$first": false,
                            "$last": true
                        }
                    ]
                },
                {
                    "race": "Ward 5",
                    "candidates": [
                        {
                            "candidate": "Ron Welper",
                            "race": "Ward 5",
                            "votes": "1019",
                            "totalvotes": "1954",
                            "votepercent": "52.15",
                            "precinctsreported": "7",
                            "precincts": "7",
                            "age": "65",
                            "education": "High school graduate of Mabel, Minn.; Waterloo barber college.",
                            "employment": "Retired barber and contractor.",
                            "community": "Helped found Neighbors Helping Neighbors neighborhood assocation; 4th Street Cruise Committee; Senior Companion Board at Hawkeye Community College; Hawkeye Valley Area Agency on Aging Board; past president of Metro Exchange Club; past member American Legion Club; past member Elk's Club.",
                            "running": "\"I'm proud of my attendance record of 99 percent. I read the material. I treat everyone equal. I would promise to do the same.\"",
                            "fun": "\"I have the curse that I'm a perfectionsist,\" which relates back to his work as a barber.",
                            "mug": "images/wloo/welper.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/ron-welper-running-for-fourth-term/article_cfd49c7d-3261-54b2-8001-1e760b59a58d.html",
                            "raceentryhead": "\"Ron Welper running for fourth term\" (10/1/2013)",
                            "quote": "\"Taxes are probably the thing that separates us the most. (Reisinger) keeps talking about the need to cut. But we've been cutting for many years and there's just no place to cut anymore.",
                            "quotedate": "10/28/2013",
                            "quotelink": "http://wcfcourier.com/news/local/govt-and-politics/experience-taxes-highlig…terloo-ward-council-race/article_5611a16a-869f-5700-9953-478e1d997c2a.html",
                            "linkonehead": "\"Lind and Morrissey win Waterloo Council seats, Welper holds onto Ward 5\" (11/5/2013)",
                            "linkone": "http://wcfcourier.com/news/local/govt-and-politics/lind-and-morrissey-win-w…-seats-welper-holds-onto/article_f7911160-4c6e-5146-a5d9-cc1e306b93c3.html",
                            "linktwohead": "\"New faces, hot races highlight Waterloo city races\" (11/3/13)",
                            "linktwo": "http://wcfcourier.com/news/local/govt-and-politics/new-faces-hot-races-highlight-waterloo-city-races/article_d614a742-c6e5-5000-ba9e-32b1c63b7e61.html",
                            "linkthreehead": "\"Clark leads Schmitt in campaign cash\" (11/3/2013)",
                            "linkthree": "http://wcfcourier.com/news/local/govt-and-politics/clark-leads-schmitt-in-campaign-cash/article_ac1dd814-bb8a-5ad0-abba-65e0c6e7f6b7.html",
                            "linkfourhead": "\"Experience, taxes highlight Waterloo Ward 5 Council race\" (10/28/2013)            ",
                            "linkfour": "http://wcfcourier.com/news/local/govt-and-politics/experience-taxes-highlig…terloo-ward-council-race/article_5611a16a-869f-5700-9953-478e1d997c2a.html",
                            "linkfivehead": "\"Waterloo City Council hopefuls introduce themselves at forum\" (10/18/2013)            ",
                            "linkfive": "http://wcfcourier.com/news/local/govt-and-politics/waterloo-city-council-ho…duce-themselves-at-forum/article_52b1b80b-cccd-53e1-8976-018a463dd338.html",
                            "linksixhead": "\"Councilman pushes for retail at Lafayette School site\" (10/18/2013)",
                            "linksix": "http://wcfcourier.com/news/local/govt-and-politics/councilman-pushes-for-re…at-lafayette-school-site/article_168da952-7551-54e8-a97e-a5e6d7ed78e7.html",
                            "linksevenhead": "",
                            "linkseven": "",
                            "versus": "TRUE",
                            "rowNumber": 7,
                            "$index": 0,
                            "$first": true,
                            "$last": false
                        },
                        {
                            "candidate": "Bob Reisinger",
                            "race": "Ward 5",
                            "votes": "935",
                            "totalvotes": "1954",
                            "votepercent": "47.85",
                            "precinctsreported": "7",
                            "precincts": "7",
                            "age": "67",
                            "education": "Waterloo Orange High graduate; attended University of Northern Iowa, three years.",
                            "employment": "Executive Vice President of Waterloo-Cedar Falls Board of Realtors",
                            "community": "Waterloo community Development Board, secretary; Black Hawk County Board of Review member; Waterloo GROW Task Force member; past president of Waterloo Jaycees; past president of Board of Realtors; past member of Waterloo Board of Adjustment and WAterloo Chamber of Commerce board.",
                            "running": "\"I feel I can use the 40-plus years of business experience, association management experience and community involvement to help guide and lead Waterloo into the future. We need more planning, improved communication, more work to lower taxes, and aggressive economic development to grow our tax base.\"",
                            "fun": "\"My hobbies are woodworking and cooking.\"",
                            "mug": "images/wloo/reisinger.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/bob-reisinger-tosses-hat…rd-waterloo-council-race/article_439aa725-1fea-5780-a927-c2973ed8007a.html",
                            "raceentryhead": "\"Bob Reisinger tosses hat into Ward 5 Waterloo council race\" (9/12/2013)",
                            "quote": "“Any business needs a plan. Where do you want to be in one year or five years? I don’t see that at the city level now.”",
                            "quotedate": "9/12/2013",
                            "quotelink": "http://wcfcourier.com/news/local/govt-and-politics/bob-reisinger-tosses-hat…rd-waterloo-council-race/article_439aa725-1fea-5780-a927-c2973ed8007a.html",
                            "linkonehead": "\"Lind and Morrissey win Waterloo Council seats, Welper holds onto Ward 5\" (11/5/2013)",
                            "linkone": "http://wcfcourier.com/news/local/govt-and-politics/lind-and-morrissey-win-w…-seats-welper-holds-onto/article_f7911160-4c6e-5146-a5d9-cc1e306b93c3.html",
                            "linktwohead": "\"New faces, hot races highlight Waterloo city races\" (11/3/13)",
                            "linktwo": "http://wcfcourier.com/news/local/govt-and-politics/new-faces-hot-races-highlight-waterloo-city-races/article_d614a742-c6e5-5000-ba9e-32b1c63b7e61.html",
                            "linkthreehead": "\"Clark leads Schmitt in campaign cash\" (11/3/2013)",
                            "linkthree": "http://wcfcourier.com/news/local/govt-and-politics/clark-leads-schmitt-in-campaign-cash/article_ac1dd814-bb8a-5ad0-abba-65e0c6e7f6b7.html",
                            "linkfourhead": "\"Experience, taxes highlight Waterloo Ward 5 Council race\" (10/28/2013)",
                            "linkfour": "http://wcfcourier.com/news/local/govt-and-politics/experience-taxes-highlig…terloo-ward-council-race/article_5611a16a-869f-5700-9953-478e1d997c2a.html",
                            "linkfivehead": "\"Waterloo City Council hopefuls introduce themselves at forum\" (10/18/2013)            ",
                            "linkfive": "http://wcfcourier.com/news/local/govt-and-politics/waterloo-city-council-ho…duce-themselves-at-forum/article_52b1b80b-cccd-53e1-8976-018a463dd338.html",
                            "linksixhead": "",
                            "linksix": "",
                            "linksevenhead": "",
                            "linkseven": "",
                            "versus": "TRUE",
                            "rowNumber": 8,
                            "$index": 1,
                            "$first": false,
                            "$last": true
                        }
                    ]
                },
                {
                    "race": "At-Large",
                    "candidates": [
                        {
                            "candidate": "Tom Lind",
                            "race": "At-Large",
                            "votes": "4533",
                            "totalvotes": "8772",
                            "votepercent": "51.68",
                            "precinctsreported": "31",
                            "precincts": "31",
                            "age": "68",
                            "education": "Bachelor of Science, The University of Iowa.",
                            "employment": "Retired from Iowa Department of Transportation; former local business owner.",
                            "community": "Formally Waterloo/Cedar Falls Symphony; Iowa Athletic Association; Peugeot National Dealer, board member; countless volunteer hours for West High and Cedar Valley Youth Soccer Association.",
                            "running": "\"I am running because, since I am recently retired, I have the opportunity to devote my full attention to the city council position and I will be able to bring years of business and public sector experience. I want to promote a culture of efficiency, transparency and sustainability in city government; and I want to simply help make Waterloo a great place to live.\"",
                            "fun": "\"I played basketball at Iowa during my freshman year.\"",
                            "mug": "images/wloo/lind.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/tom-lind-announces-bid-f…ge-waterloo-council-seat/article_de102eb3-b3ef-5fdf-9bf9-e2b9e4788069.html",
                            "raceentryhead": "\"Tom Lind announces bid for at-large Waterloo council seat\" (9/30/2013)",
                            "quote": "\"We cannot continue to raise taxes to buy stuff that maybe we just want. We have to get back to just the needs things.\"",
                            "quotedate": "10/18/2013",
                            "quotelink": "http://wcfcourier.com/news/local/govt-and-politics/waterloo-city-council-ho…duce-themselves-at-forum/article_52b1b80b-cccd-53e1-8976-018a463dd338.html",
                            "linkonehead": "\"Lind and Morrissey win Waterloo Council seats, Welper holds onto Ward 5\" (11/5/2013)",
                            "linkone": "http://wcfcourier.com/news/local/govt-and-politics/lind-and-morrissey-win-w…-seats-welper-holds-onto/article_f7911160-4c6e-5146-a5d9-cc1e306b93c3.html",
                            "linktwohead": "\"New faces, hot races highlight Waterloo city races\" (11/3/13)",
                            "linktwo": "http://wcfcourier.com/news/local/govt-and-politics/new-faces-hot-races-highlight-waterloo-city-races/article_d614a742-c6e5-5000-ba9e-32b1c63b7e61.html",
                            "linkthreehead": "\"Clark leads Schmitt in campaign cash\" (11/3/2013)",
                            "linkthree": "http://wcfcourier.com/news/local/govt-and-politics/clark-leads-schmitt-in-campaign-cash/article_ac1dd814-bb8a-5ad0-abba-65e0c6e7f6b7.html",
                            "linkfourhead": "\"At-large Waterloo council candidates lay out budget goals\" (10/30/2013)",
                            "linkfour": "http://wcfcourier.com/news/local/govt-and-politics/at-large-waterloo-counci…tes-lay-out-budget-goals/article_01879774-76ce-5111-9e11-e2148c0f08f1.html",
                            "linkfivehead": "\"Waterloo City Council hopefuls introduce themselves at forum\" (10/18/2013)            ",
                            "linkfive": "http://wcfcourier.com/news/local/govt-and-politics/waterloo-city-council-ho…duce-themselves-at-forum/article_52b1b80b-cccd-53e1-8976-018a463dd338.html",
                            "linksixhead": "",
                            "linksix": "",
                            "linksevenhead": "",
                            "linkseven": "",
                            "versus": "TRUE",
                            "rowNumber": 9,
                            "$index": 0,
                            "$first": true,
                            "$last": false
                        },
                        {
                            "candidate": "Tavis Hall",
                            "race": "At-Large",
                            "votes": "4239",
                            "totalvotes": "8772",
                            "votepercent": "48.32",
                            "precinctsreported": "31",
                            "precincts": "31",
                            "age": "28",
                            "education": "Waterloo West High School; Hawkeye Community College associates program",
                            "employment": "Regional Outreach Representative, Office of Congressman Bruce Braley",
                            "community": "Cedar Valley Next Generation Rotary; Waterloo Convention & Visitors Board, vice-chair; NAACP, former chair of political empowerment committee and current member; County Democratic Party, former vice-chair and current member.",
                            "running": "\"I love our city. I was born and raised here and this is where my wife and I are raising our family. I have a tremendous amout of pride in our city and I know that with a focus on helping create better jobs, safer streets and smarter budgets, I will be able to help play an important roll in making Waterloo an even better city to live, work and raise a family. I have dedicated my professional life to public policy and improving people's lives and I believe my skillset will lend itself well to serving the citizens of our city.\" ",
                            "fun": "\"I am typing the answers to these questions while on a subway in New York City on my honeymoon.\"",
                            "mug": "images/wloo/hall.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/tavis-hall-announces-bid…or-at-large-council-seat/article_20334d5f-2551-5962-bd38-7c5759f4bc4f.html",
                            "raceentryhead": "\"Tavis Hall announces bid for at-large council seat\" (8/28/2013)",
                            "quote": "\"While I have a tremendous amount of pride in our city, I believe that  we can do better and that we must do better to see the sort of growth and development that is needed to succeed.\"",
                            "quotedate": "8/28/2013",
                            "quotelink": "http://wcfcourier.com/news/local/govt-and-politics/tavis-hall-announces-bid…or-at-large-council-seat/article_20334d5f-2551-5962-bd38-7c5759f4bc4f.html",
                            "linkonehead": "\"Lind and Morrissey win Waterloo Council seats, Welper holds onto Ward 5\" (11/5/2013)",
                            "linkone": "http://wcfcourier.com/news/local/govt-and-politics/lind-and-morrissey-win-w…-seats-welper-holds-onto/article_f7911160-4c6e-5146-a5d9-cc1e306b93c3.html",
                            "linktwohead": "\"New faces, hot races highlight Waterloo city races\" (11/3/13)",
                            "linktwo": "http://wcfcourier.com/news/local/govt-and-politics/new-faces-hot-races-highlight-waterloo-city-races/article_d614a742-c6e5-5000-ba9e-32b1c63b7e61.html",
                            "linkthreehead": "\"Clark leads Schmitt in campaign cash\" (11/3/2013)",
                            "linkthree": "http://wcfcourier.com/news/local/govt-and-politics/clark-leads-schmitt-in-campaign-cash/article_ac1dd814-bb8a-5ad0-abba-65e0c6e7f6b7.html",
                            "linkfourhead": "\"Waterloo city candidates face off at KBBG forum\" (11/3/2013)",
                            "linkfour": "http://wcfcourier.com/news/local/govt-and-politics/waterloo-city-candidates-face-off-at-kbbg-forum/article_cd26c02f-35db-5cc9-8db3-67fe5b09f416.html",
                            "linkfivehead": "\"At-large Waterloo council candidates lay out budget goals\" (10/30/2013)           ",
                            "linkfive": "http://wcfcourier.com/news/local/govt-and-politics/at-large-waterloo-counci…tes-lay-out-budget-goals/article_01879774-76ce-5111-9e11-e2148c0f08f1.html",
                            "linksixhead": "\"Waterloo City Council hopefuls introduce themselves at forum\" (10/18/2013)            ",
                            "linksix": "http://wcfcourier.com/news/local/govt-and-politics/waterloo-city-council-ho…duce-themselves-at-forum/article_52b1b80b-cccd-53e1-8976-018a463dd338.html",
                            "linksevenhead": "",
                            "linkseven": "",
                            "versus": "TRUE",
                            "rowNumber": 10,
                            "$index": 1,
                            "$first": false,
                            "$last": true
                        }
                    ]
                },
                {
                    "race": "Issue: Tax levy for Grout",
                    "candidates": [
                        {
                            "candidate": "Yes",
                            "race": "Issue: Tax levy for Grout",
                            "votes": "4167",
                            "totalvotes": "8985",
                            "votepercent": "46.38",
                            "precinctsreported": "31",
                            "precincts": "31",
                            "age": "",
                            "education": "",
                            "employment": "",
                            "community": "",
                            "running": "",
                            "fun": "",
                            "mug": "images/wloo/grout.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/voters-reject-tax-for-grout-museum-district/article_2055bb48-13e7-5503-94bf-188c0bde96ef.html",
                            "raceentryhead": "",
                            "quote": "",
                            "quotedate": "",
                            "quotelink": "",
                            "linkonehead": "",
                            "linkone": "",
                            "linktwohead": "",
                            "linktwo": "",
                            "linkthreehead": "",
                            "linkthree": "",
                            "linkfourhead": "",
                            "linkfour": "",
                            "linkfivehead": "",
                            "linkfive": "",
                            "linksixhead": "",
                            "linksix": "",
                            "linksevenhead": "",
                            "linkseven": "",
                            "versus": "",
                            "rowNumber": 11
                        },
                        {
                            "candidate": "No",
                            "race": "Issue: Tax levy for Grout",
                            "votes": "4818",
                            "totalvotes": "8985",
                            "votepercent": "53.62",
                            "precinctsreported": "31",
                            "precincts": "31",
                            "age": "",
                            "education": "",
                            "employment": "",
                            "community": "",
                            "running": "",
                            "fun": "",
                            "mug": "images/wloo/grout.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/voters-reject-tax-for-grout-museum-district/article_2055bb48-13e7-5503-94bf-188c0bde96ef.html",
                            "raceentryhead": "",
                            "quote": "",
                            "quotedate": "",
                            "quotelink": "",
                            "linkonehead": "",
                            "linkone": "",
                            "linktwohead": "",
                            "linktwo": "",
                            "linkthreehead": "",
                            "linkthree": "",
                            "linkfourhead": "",
                            "linkfour": "",
                            "linkfivehead": "",
                            "linkfive": "",
                            "linksixhead": "",
                            "linksix": "",
                            "linksevenhead": "",
                            "linkseven": "",
                            "versus": "",
                            "rowNumber": 12
                        }
                    ]
                },
                {
                    "race": "Issue: Local option sales tax (contiguous cities)",
                    "candidates": [
                        {
                            "candidate": "Yes",
                            "race": "Issue: Local option sales tax (contiguous cities)",
                            "votes": "10392",
                            "totalvotes": "13845",
                            "votepercent": "75.06",
                            "precinctsreported": "53",
                            "precincts": "53",
                            "age": "",
                            "education": "",
                            "employment": "",
                            "community": "",
                            "running": "",
                            "fun": "",
                            "mug": "images/wloo/localoption.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/county-voters-ok--year-local-sales-tax-extension/article_917d80d4-6487-5bd4-9585-65fb9111a4eb.html",
                            "raceentryhead": "",
                            "quote": "",
                            "quotedate": "",
                            "quotelink": "",
                            "linkonehead": "",
                            "linkone": "",
                            "linktwohead": "",
                            "linktwo": "",
                            "linkthreehead": "",
                            "linkthree": "",
                            "linkfourhead": "",
                            "linkfour": "",
                            "linkfivehead": "",
                            "linkfive": "",
                            "linksixhead": "",
                            "linksix": "",
                            "linksevenhead": "",
                            "linkseven": "",
                            "versus": "",
                            "rowNumber": 13
                        },
                        {
                            "candidate": "No",
                            "race": "Issue: Local option sales tax (contiguous cities)",
                            "votes": "3453",
                            "totalvotes": "13845",
                            "votepercent": "24.94",
                            "precinctsreported": "53",
                            "precincts": "53",
                            "age": "",
                            "education": "",
                            "employment": "",
                            "community": "",
                            "running": "",
                            "fun": "",
                            "mug": "images/wloo/localoption.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/county-voters-ok--year-local-sales-tax-extension/article_917d80d4-6487-5bd4-9585-65fb9111a4eb.html",
                            "raceentryhead": "",
                            "quote": "",
                            "quotedate": "",
                            "quotelink": "",
                            "linkonehead": "",
                            "linkone": "",
                            "linktwohead": "",
                            "linktwo": "",
                            "linkthreehead": "",
                            "linkthree": "",
                            "linkfourhead": "",
                            "linkfour": "",
                            "linkfivehead": "",
                            "linkfive": "",
                            "linksixhead": "",
                            "linksix": "",
                            "linksevenhead": "",
                            "linkseven": "",
                            "versus": "",
                            "rowNumber": 14
                        }
                    ]
                }
            ]
        },
        {
            "city": "Cedar Falls",
            "races": [
                {
                    "race": "Ward 1",
                    "candidates": [
                        {
                            "candidate": "Mark Miller",
                            "race": "Ward 1",
                            "votes": "789",
                            "totalvotes": "1214",
                            "votepercent": "64.99",
                            "precinctsreported": "4",
                            "precincts": "4",
                            "age": "37",
                            "education": "University of Northern Iowa and Hawkeye Community College",
                            "employment": "Owns E360 Building Co. Inc.",
                            "community": "President of the North Cedar Neighborhood Association",
                            "running": "\"It's the next step. I've been involved in the community and I've always wanted to take the next, keep moving forward.\" ",
                            "fun": "\"I have a twin brother.”",
                            "mug": "images/cf/miller.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/cedar-falls-businessman-seeks-city-council-seat/article_e3bca11f-9a64-5c77-ba36-fe364374e6a7.html",
                            "raceentryhead": "\"Cedar Falls businessman seeks City Council seat\" (8/12/2013)",
                            "quote": "“We pay taxes in northern Cedar Falls just like everyone else so our dollars are essentially going to push more water on the city in the  event of another flood. A little bit of investment, I think, might be necessary in northern Cedar Falls.",
                            "quotedate": "10/23/2013",
                            "quotelink": "http://wcfcourier.com/news/local/govt-and-politics/full-time-or-part-time-m…r-subject-of-cedar-falls/article_7a3ea7f9-f5c8-556d-b3aa-51e2826a3fe8.html",
                            "linkonehead": "\"Crews, Miller, deBuhr elected in Cedar Falls\" (11/5/2013)\n",
                            "linkone": "http://wcfcourier.com/news/local/govt-and-politics/cedar-falls-election-res…s-crews-re-elected-mayor/article_cbc1c2c3-ae8f-5a19-89c2-88a5d58c33e9.html",
                            "linktwohead": "\"Full-time or part-time mayor subject of Cedar Falls council debate\" (10/23/2013)",
                            "linktwo": "http://wcfcourier.com/news/local/govt-and-politics/full-time-or-part-time-m…r-subject-of-cedar-falls/article_7a3ea7f9-f5c8-556d-b3aa-51e2826a3fe8.html",
                            "linkthreehead": "\"Cedar Falls Council candidiates Hartley and Miller highlight budget concerns\" (10/18/2013)",
                            "linkthree": "http://wcfcourier.com/news/local/govt-and-politics/cedar-falls-council-cand…ighlight-budget-concerns/article_423d9b58-5b91-534d-9cd3-ad7120ef8a7f.html",
                            "linkfourhead": "\"Cedar Falls City Council candidate roundup\" (9/20/2013)",
                            "linkfour": "http://wcfcourier.com/news/local/govt-and-politics/cedar-falls-city-council-candidate-roundup/article_4f1a0fff-1d76-5bf1-bebb-5717f4aa5f9b.html",
                            "versus": "TRUE",
                            "rowNumber": 1,
                            "$index": 0,
                            "$first": true,
                            "$last": false
                        },
                        {
                            "candidate": "Dave Hartley",
                            "race": "Ward 1",
                            "votes": "425",
                            "totalvotes": "1214",
                            "votepercent": "35.01",
                            "precinctsreported": "4",
                            "precincts": "4",
                            "age": "45",
                            "education": "Hawkeye community college",
                            "employment": "Sales Manager at Woolverton Printing",
                            "community": "A member of Cedar Falls Lions Club",
                            "running": "“There’s a time in everyone’s life where I think they should step up and serve in some capacity. I’ve always said this is what I wanted to do.”",
                            "fun": "\"I play the drums in a band called the Snozzberries.\"",
                            "mug": "images/cf/hartley.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/hartley-will-run-for-cedar-falls-council/article_3f1fe67d-2bd1-55d7-85a7-b42d585b34fc.html",
                            "raceentryhead": "\"Hartley will run for Cedar Falls council\" (8/5/2013)\n",
                            "quote": "\"My goal will be to have Cedar Falls continue to operate within a balanced budget, strive to lower taxes, to be a good steward of the city revenues.\" ",
                            "quotedate": "8/5/2013",
                            "quotelink": "http://wcfcourier.com/news/local/hartley-will-run-for-cedar-falls-council/article_3f1fe67d-2bd1-55d7-85a7-b42d585b34fc.html",
                            "linkonehead": "\"Crews, Miller, deBuhr elected in Cedar Falls\" (11/5/2013)",
                            "linkone": "http://wcfcourier.com/news/local/govt-and-politics/cedar-falls-election-res…s-crews-re-elected-mayor/article_cbc1c2c3-ae8f-5a19-89c2-88a5d58c33e9.html",
                            "linktwohead": "\"Full-time or part-time mayor subject of Cedar Falls council debate\" (10/23/2013)",
                            "linktwo": "http://wcfcourier.com/news/local/govt-and-politics/full-time-or-part-time-m…r-subject-of-cedar-falls/article_7a3ea7f9-f5c8-556d-b3aa-51e2826a3fe8.html",
                            "linkthreehead": "\"Cedar Falls Council candidiates Hartley and Miller highlight budget concerns\" (10/18/2013)",
                            "linkthree": "http://wcfcourier.com/news/local/govt-and-politics/cedar-falls-council-cand…ighlight-budget-concerns/article_423d9b58-5b91-534d-9cd3-ad7120ef8a7f.html",
                            "linkfourhead": "\"Cedar Falls City Council candidate roundup\" (9/20/2013)",
                            "linkfour": "http://wcfcourier.com/news/local/govt-and-politics/cedar-falls-city-council-candidate-roundup/article_4f1a0fff-1d76-5bf1-bebb-5717f4aa5f9b.html",
                            "versus": "TRUE",
                            "rowNumber": 2,
                            "$index": 1,
                            "$first": false,
                            "$last": true
                        }
                    ]
                },
                {
                    "race": "Ward 2",
                    "candidates": [
                        {
                            "candidate": "Susan deBuhr",
                            "race": "Ward 2",
                            "votes": "417",
                            "totalvotes": "610",
                            "votepercent": "68.36",
                            "precinctsreported": "4",
                            "precincts": "4",
                            "age": "52",
                            "education": "Morningsdale College in Sioux City",
                            "employment": "co-manages family business Color Glo. ",
                            "community": "Worked on fundraising efforts for Altrusa. ",
                            "running": "“I feel a deep loyalty to the people of my ward.”",
                            "fun": "\"I once worked as an Iowa State Trooper.\"",
                            "mug": "images/cf/debuhr.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/council-races-shaping-up-in-cedar-falls/article_696b703f-304d-5bec-ac4b-93c4ef63f74b.html",
                            "raceentryhead": "\"Council races shaping up in Cedar Falls\" (9/2/2013)",
                            "quote": "“I think the length of time and experience I’ve had on the council is going to be beneficial in the difficult years ahead”",
                            "quotedate": "9/20/2013",
                            "quotelink": "http://wcfcourier.com/news/local/govt-and-politics/cedar-falls-city-council-candidate-roundup/article_4f1a0fff-1d76-5bf1-bebb-5717f4aa5f9b.html",
                            "linkonehead": "\"Crews, Miller, deBuhr elected in Cedar Falls\" (11/5/2013)",
                            "linkone": "http://wcfcourier.com/news/local/govt-and-politics/cedar-falls-election-res…s-crews-re-elected-mayor/article_cbc1c2c3-ae8f-5a19-89c2-88a5d58c33e9.html",
                            "linktwohead": "\"Full-time or part-time mayor subject of Cedar Falls council debate\" (10/23/2013)",
                            "linktwo": "http://wcfcourier.com/news/local/govt-and-politics/full-time-or-part-time-m…r-subject-of-cedar-falls/article_7a3ea7f9-f5c8-556d-b3aa-51e2826a3fe8.html",
                            "linkthreehead": "\"Ward 2 candidates concentrate on Meadows subdivision\" (10/10/2013)",
                            "linkthree": "http://wcfcourier.com/news/local/govt-and-politics/ward-candidates-concentr…e-on-meadows-subdivision/article_180eac94-400e-5384-b535-67098eac88b0.html",
                            "linkfourhead": "\"Cedar Falls City Council candidate roundup\" (9/20/2013)",
                            "linkfour": "http://wcfcourier.com/news/local/govt-and-politics/cedar-falls-city-council-candidate-roundup/article_4f1a0fff-1d76-5bf1-bebb-5717f4aa5f9b.html",
                            "versus": "TRUE",
                            "rowNumber": 3,
                            "$index": 0,
                            "$first": true,
                            "$last": false
                        },
                        {
                            "candidate": "Mare Madsen Schmidt",
                            "race": "Ward 2",
                            "votes": "193",
                            "totalvotes": "610",
                            "votepercent": "31.64",
                            "precinctsreported": "4",
                            "precincts": "4",
                            "age": "57",
                            "education": "University of Northern Iowa",
                            "employment": "Owns Art Store & More",
                            "community": "N/A",
                            "running": "“I love being on city council because it makes me feel useful if I can help somebody.”",
                            "fun": "“I can speak three languages. English, Spanish, and German.”",
                            "mug": "images/cf/schmidt.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/council-races-shaping-up-in-cedar-falls/article_696b703f-304d-5bec-ac4b-93c4ef63f74b.html",
                            "raceentryhead": "\"Council races shaping up in Cedar Falls\" (9/2/2013)",
                            "quote": "“I’m very excited about the prospect of serving the people of Ward .I’ve met so many genuinely nice people out there. That really gets me excited about helping out in any way I can.” ",
                            "quotedate": "10/10/2013",
                            "quotelink": "http://wcfcourier.com/news/local/govt-and-politics/ward-candidates-concentr…e-on-meadows-subdivision/article_180eac94-400e-5384-b535-67098eac88b0.html",
                            "linkonehead": "\"Crews, Miller, deBuhr elected in Cedar Falls\" (11/5/2013)",
                            "linkone": "http://wcfcourier.com/news/local/govt-and-politics/cedar-falls-election-res…s-crews-re-elected-mayor/article_cbc1c2c3-ae8f-5a19-89c2-88a5d58c33e9.html",
                            "linktwohead": "\"Full-time or part-time mayor subject of Cedar Falls council debate\" (10/23/2013)",
                            "linktwo": "http://wcfcourier.com/news/local/govt-and-politics/full-time-or-part-time-m…r-subject-of-cedar-falls/article_7a3ea7f9-f5c8-556d-b3aa-51e2826a3fe8.html",
                            "linkthreehead": "\"Ward 2 candidates concentrate on Meadows subdivision\" (10/10/2013)",
                            "linkthree": "http://wcfcourier.com/news/local/govt-and-politics/ward-candidates-concentr…e-on-meadows-subdivision/article_180eac94-400e-5384-b535-67098eac88b0.html",
                            "linkfourhead": "\"Cedar Falls City Council candidate roundup\" (9/20/2013)",
                            "linkfour": "http://wcfcourier.com/news/local/govt-and-politics/cedar-falls-city-council-candidate-roundup/article_4f1a0fff-1d76-5bf1-bebb-5717f4aa5f9b.html",
                            "versus": "TRUE",
                            "rowNumber": 4,
                            "$index": 1,
                            "$first": false,
                            "$last": true
                        }
                    ]
                },
                {
                    "race": "Issue: Local option sales tax (contiguous cities)",
                    "candidates": [
                        {
                            "candidate": "Yes",
                            "race": "Issue: Local option sales tax (contiguous cities)",
                            "votes": "10392",
                            "totalvotes": "13845",
                            "votepercent": "75.06",
                            "precinctsreported": "53",
                            "precincts": "53",
                            "age": "",
                            "education": "",
                            "employment": "",
                            "community": "",
                            "running": "",
                            "fun": "",
                            "mug": "images/wloo/localoption.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/county-voters-ok--year-local-sales-tax-extension/article_917d80d4-6487-5bd4-9585-65fb9111a4eb.html",
                            "raceentryhead": "",
                            "quote": "",
                            "quotedate": "",
                            "quotelink": "",
                            "linkonehead": "",
                            "linkone": "",
                            "linktwohead": "",
                            "linktwo": "",
                            "linkthreehead": "",
                            "linkthree": "",
                            "linkfourhead": "",
                            "linkfour": "",
                            "versus": "",
                            "rowNumber": 5
                        },
                        {
                            "candidate": "No",
                            "race": "Issue: Local option sales tax (contiguous cities)",
                            "votes": "3453",
                            "totalvotes": "13845",
                            "votepercent": "24.94",
                            "precinctsreported": "53",
                            "precincts": "53",
                            "age": "",
                            "education": "",
                            "employment": "",
                            "community": "",
                            "running": "",
                            "fun": "",
                            "mug": "images/wloo/localoption.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/county-voters-ok--year-local-sales-tax-extension/article_917d80d4-6487-5bd4-9585-65fb9111a4eb.html",
                            "raceentryhead": "",
                            "quote": "",
                            "quotedate": "",
                            "quotelink": "",
                            "linkonehead": "",
                            "linkone": "",
                            "linktwohead": "",
                            "linktwo": "",
                            "linkthreehead": "",
                            "linkthree": "",
                            "linkfourhead": "",
                            "linkfour": "",
                            "versus": "",
                            "rowNumber": 6
                        }
                    ]
                }
            ]
        },
        {
            "city": "Waverly",
            "races": [
                {
                    "race": "Mayor",
                    "candidates": [
                        {
                            "candidate": "Charles Infelt",
                            "race": "Mayor",
                            "votes": "1322",
                            "totalvotes": "1707",
                            "votepercent": "77.45",
                            "precinctsreported": "5",
                            "precincts": "5",
                            "age": "69",
                            "education": "M.A. Theology, Lutheran School of Theology, Chicago",
                            "employment": "Retired pastor, Holy Family Church, Chicago",
                            "community": "Wartburg Community Symphony Orchestra board member; Rotary Club",
                            "running": "I have a lot of experience dealing with systems and dealing with government. I want to help Waverly maintain a quality of life that is affordable. When we bring new people to the town, that spreads the tax base. If we pull together, then we have a great force building the future.",
                            "fun": "I play guitar",
                            "mug": "images/waverly/infelt.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/state-and-regional/waverly-city-council-incumbents-face-challengers/article_d881e4ed-92f6-5826-831d-83411a4610f4.html",
                            "raceentryhead": "\"Waverly city council incumbents face challengers\" (9/22/2013)",
                            "quote": "\"When we bring new people to the town, that spreads the tax base. If we pull together, then we have a great force building the future.\"",
                            "quotedate": "10/23/2013",
                            "linkonehead": "\"Infelt elected mayor of Waverly; Gade and Reznicek win ward races\" (11/5/2013)\n",
                            "linkone": "http://wcfcourier.com/news/local/govt-and-politics/infelt-elected-mayor-of-waverly/article_aaa91849-cb02-5538-a090-c286d82efc9f.html",
                            "linktwohead": "\"Two seek role to lead Waverly\" (11/4/2013)",
                            "linktwo": "http://wcfcourier.com/news/local/govt-and-politics/two-seek-role-to-lead-waverly/article_1393d1fb-b114-5766-ac27-b1961f45fc19.html",
                            "versus": "TRUE",
                            "rowNumber": 1,
                            "$index": 0,
                            "$first": true,
                            "$last": false
                        },
                        {
                            "candidate": "Duane Liddle",
                            "race": "Mayor",
                            "votes": "385",
                            "totalvotes": "1707",
                            "votepercent": "22.55",
                            "precinctsreported": "5",
                            "precincts": "5",
                            "age": "60",
                            "education": "High School graduate, New Hampton; one year at Area1 Vocational Technical School, Calmar; CNC Machining, Hawk Community College.",
                            "employment": " Industrial painter; four years as a Waverly Councilman-at Large, owner and founder of multiple business endeavors -- a property management company, an auto body shop, repairing and restoring gel coating on fiberglass boats.",
                            "community": "Real World Education, founder - helping teens apply classroom lessons to real life; Waverly Skaters, a teen mentoring group; Waverly Heritage Days committee; Board of Directors Ira Sturdevant House.",
                            "running": "I am running for mayor to control the cost of living in Waverly while listening to the voices of all citizens to determine the direction of their government. I have participated at Waverly City Council meetings since 1998. I have participated in each of the past nine Waverly budget workshops. A public works recommendation for 71 percent of households to have city-owned garbage containers comes after years of the solid waste fund showing steady increases of excess cash in the fund.",
                            "fun": "My first meeting as a Councilman-at-Large, I found three of the chairs for the council members could not be raised in height. I machined a steel replacement part for the three broken chairs. The chairs work just fine and are in use today. ",
                            "mug": "images/waverly/liddle.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/state-and-regional/waverly-city-council-incumbents-face-challengers/article_d881e4ed-92f6-5826-831d-83411a4610f4.html",
                            "raceentryhead": "\"Waverly city council incumbents face challengers\" (9/22/2013)",
                            "quote": "\"I am running for mayor to control the cost of living in Waverly while listening to the voices of all citizens to determine the direction of their government.\"",
                            "quotedate": "10/23/2013",
                            "linkonehead": "\"Infelt elected mayor of Waverly; Gade and Reznicek win ward races\" (11/5/2013)",
                            "linkone": "http://wcfcourier.com/news/local/govt-and-politics/infelt-elected-mayor-of-waverly/article_aaa91849-cb02-5538-a090-c286d82efc9f.html",
                            "linktwohead": "\"Two seek role to lead Waverly\" (11/4/2013)",
                            "linktwo": "http://wcfcourier.com/news/local/govt-and-politics/two-seek-role-to-lead-waverly/article_1393d1fb-b114-5766-ac27-b1961f45fc19.html",
                            "versus": "TRUE",
                            "rowNumber": 2,
                            "$index": 1,
                            "$first": false,
                            "$last": true
                        }
                    ]
                },
                {
                    "race": "Ward 3",
                    "candidates": [
                        {
                            "candidate": "Wes Gade",
                            "race": "Ward 3",
                            "votes": "106",
                            "totalvotes": "192",
                            "votepercent": "55.21",
                            "precinctsreported": "1",
                            "precincts": "1",
                            "age": "35",
                            "education": "B.A., Computer Science, Wartburg College; AA in Electronic Engineering, Hawkeye Community College",
                            "employment": "Database Administrator at Network Control, Waverly",
                            "community": "Bremer County Republicans chairman",
                            "running": "I have always been very concerned about Waverly residents’ quality of life, small businesses, and property taxes. Lowering property taxes is a vital part of my plan.  It will help current citizens keep more of the money they earn, and it will encourage families to move to Waverly. ",
                            "fun": "I collect coins; something I picked up from my grandfather.",
                            "mug": "images/waverly/gade.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/state-and-regional/waverly-city-council-incumbents-face-challengers/article_d881e4ed-92f6-5826-831d-83411a4610f4.html",
                            "raceentryhead": "\"Waverly city council incumbents face challengers\" (9/22/2013)",
                            "quote": "\"Lowering property taxes is a vital part of my plan.  It will help current citizens keep more of the money they earn, and it will encourage families to move to Waverly.\"",
                            "quotedate": "10/23/2013",
                            "linkonehead": "\"Infelt elected mayor of Waverly; Gade and Reznicek win ward races\" (11/5/2013)",
                            "linkone": "http://wcfcourier.com/news/local/govt-and-politics/infelt-elected-mayor-of-waverly/article_aaa91849-cb02-5538-a090-c286d82efc9f.html",
                            "linktwohead": "\"Wartburg student Jacob Martin challenges Gade for Waverly Ward 3 council seat\" (11/3/2013)",
                            "linktwo": "http://wcfcourier.com/news/local/govt-and-politics/wartburg-student-jacob-m…for-waverly-ward-council/article_6c4c7c45-4f8b-5f4a-b282-626ee0dc1540.html",
                            "versus": "TRUE",
                            "rowNumber": 3,
                            "$index": 0,
                            "$first": true,
                            "$last": false
                        },
                        {
                            "candidate": "Jacob Martin",
                            "race": "Ward 3",
                            "votes": "86",
                            "totalvotes": "192",
                            "votepercent": "44.79",
                            "precinctsreported": "1",
                            "precincts": "1",
                            "age": "20",
                            "education": "Third-year student at Wartburg College pursuing a BA in political science and business administration.",
                            "employment": "Junior, Wartburg College",
                            "community": "Wartburg Castle Singers; Wartburg Pre-Law Club",
                            "running": "I am running for city council because I want to enact the changes people have been asking for. Ward 3 residents have been talking about infrastructure and taxation issues for quite some time, and I am ready to step up and pursue the best interest of Ward 3 and Waverly as a whole. ",
                            "fun": "I have visited 24 different states and eight foreign countries.",
                            "mug": "images/waverly/martin.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/state-and-regional/waverly-city-council-incumbents-face-challengers/article_d881e4ed-92f6-5826-831d-83411a4610f4.html",
                            "raceentryhead": "\"Waverly city council incumbents face challengers\" (9/22/2013)",
                            "quote": "\"Ward 3 residents have been talking about infrastructure and taxation issues for quite some time, and I am ready to step up and pursue the best interest of Ward 3 and Waverly as a whole\"",
                            "quotedate": "10/23/2013",
                            "linkonehead": "\"Infelt elected mayor of Waverly; Gade and Reznicek win ward races\" (11/5/2013)",
                            "linkone": "http://wcfcourier.com/news/local/govt-and-politics/infelt-elected-mayor-of-waverly/article_aaa91849-cb02-5538-a090-c286d82efc9f.html",
                            "linktwohead": "\"Wartburg student Jacob Martin challenges Gade for Waverly Ward 3 council seat\" (11/3/2013)",
                            "linktwo": "http://wcfcourier.com/news/local/govt-and-politics/wartburg-student-jacob-m…for-waverly-ward-council/article_6c4c7c45-4f8b-5f4a-b282-626ee0dc1540.html",
                            "versus": "TRUE",
                            "rowNumber": 4,
                            "$index": 1,
                            "$first": false,
                            "$last": true
                        }
                    ]
                },
                {
                    "race": "At-Large",
                    "candidates": [
                        {
                            "candidate": "David Reznicek",
                            "race": "At-Large",
                            "votes": "1213",
                            "totalvotes": "1592",
                            "votepercent": "76.19",
                            "precinctsreported": "5",
                            "precincts": "5",
                            "age": "46",
                            "education": "M.S., Agricultural Economics, Purdue University; MBA, Indiana University; B.S., University of Nebraska ",
                            "employment": "Product Market Development program manager, John Deere",
                            "community": "Waverly Area Small Business Incubator and Consultation Center, vice president; Economic Development Commission, former chair of the commission; Waverly Shellrock School District Advisory Committee; Youth Basketball coach",
                            "running": "I want to be on the Council to be in a position to take the necessary steps to ensure Waverly is a competitive place for new business and new residents to locate as well as ensure current businesses and residents can afford to stay here.  We can't just talk about high level plans, robust economic development strategies must be in place to drive sustainable growth, and leadership must have the background to make things happen.  Waverly requires a proactive approach to city planning.  I have the experience to make things happen in a financially sustainable way. ",
                            "fun": "I'm den leader of Pack 90 Cub Scouts in Waverly",
                            "mug": "images/waverly/reznicek.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/state-and-regional/waverly-city-council-incumbents-face-challengers/article_d881e4ed-92f6-5826-831d-83411a4610f4.html",
                            "raceentryhead": "\"Waverly city council incumbents face challengers\" (9/22/2013)",
                            "quote": "\"We can't just talk about high level plans, robust economic development strategies must be in place to drive sustainable growth, and leadership must have the background to make things happen.  Waverly requires a proactive approach to city planning.\"",
                            "quotedate": "10/23/2013",
                            "linkonehead": "\"Infelt elected mayor of Waverly; Gade and Reznicek win ward races\" (11/5/2013)",
                            "linkone": "http://wcfcourier.com/news/local/govt-and-politics/infelt-elected-mayor-of-waverly/article_aaa91849-cb02-5538-a090-c286d82efc9f.html",
                            "linktwohead": "\"Two candidates competing for Waverly's at-large council seat\" (10/30/2013)",
                            "linktwo": "http://wcfcourier.com/news/local/two-candidates-competing-for-waverly-s-at-large-council-seat/article_8ac4c15c-c9e4-5fef-9971-e24085024509.html",
                            "versus": "TRUE",
                            "rowNumber": 5,
                            "$index": 0,
                            "$first": true,
                            "$last": false
                        },
                        {
                            "candidate": "Christopher Skuster",
                            "race": "At-Large",
                            "votes": "379",
                            "totalvotes": "1592",
                            "votepercent": "23.81",
                            "precinctsreported": "5",
                            "precincts": "5",
                            "age": "30",
                            "education": "B.A., Community Sociology, Wartburg College",
                            "employment": "Family Care Coordinator with Families First",
                            "community": "Care & Repair - offers assistance to those who need help with manual labor around home; Salvation Army Adopt-A-Family",
                            "running": "As a new dad, I want to make a difference in my community. Having spent almost a decade as a police officer, I understand the importance of keeping our city safe as it continues to grow. My background in law enforcement and social work, as well as my ability to relate to others, is a valuable asset for City Council. It would be an honor to listen and represent people of Waverly.",
                            "fun": "I brew my own beer.",
                            "mug": "images/waverly/skuster.jpg",
                            "raceentry": "http://wcfcourier.com/news/local/state-and-regional/waverly-city-council-incumbents-face-challengers/article_d881e4ed-92f6-5826-831d-83411a4610f4.html",
                            "raceentryhead": "\"Waverly city council incumbents face challengers\" (9/22/2013)",
                            "quote": "\"My background in law enforcement and social work, as well as my ability to relate to others, is a valuable asset for City Council.\"",
                            "quotedate": "10/23/2013",
                            "linkonehead": "\"Infelt elected mayor of Waverly; Gade and Reznicek win ward races\" (11/5/2013)",
                            "linkone": "http://wcfcourier.com/news/local/govt-and-politics/infelt-elected-mayor-of-waverly/article_aaa91849-cb02-5538-a090-c286d82efc9f.html",
                            "linktwohead": "\"Two candidates competing for Waverly's at-large council seat\" (10/30/2013)",
                            "linktwo": "http://wcfcourier.com/news/local/two-candidates-competing-for-waverly-s-at-large-council-seat/article_8ac4c15c-c9e4-5fef-9971-e24085024509.html",
                            "versus": "TRUE",
                            "rowNumber": 6,
                            "$index": 1,
                            "$first": false,
                            "$last": true
                        }
                    ]
                }
            ]
        },
        {
            "city": "Other Cities",
            "races": [
                {
                    "race": "Dunkerton: Mayor",
                    "candidates": [
                        {
                            "candidate": "Edward Jessen",
                            "race": "Dunkerton: Mayor",
                            "votes": "196",
                            "totalvotes": "286",
                            "votepercent": "68.53",
                            "precinctsreported": "2",
                            "precincts": "2",
                            "mug": "images/other/jessen.jpg",
                            "nobio": "TRUE",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/area-election-roundup-in…n-dunkerton-evansdale-la/article_08bf2605-1b46-542d-937d-baadf4bcdd82.html",
                            "versus": "TRUE",
                            "rowNumber": 1,
                            "$index": 0,
                            "$first": true,
                            "$last": false
                        },
                        {
                            "candidate": "Michael Schares",
                            "race": "Dunkerton: Mayor",
                            "votes": "90",
                            "totalvotes": "286",
                            "votepercent": "31.47",
                            "precinctsreported": "2",
                            "precincts": "2",
                            "mug": "images/other/schares.jpg",
                            "nobio": "TRUE",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/area-election-roundup-in…n-dunkerton-evansdale-la/article_08bf2605-1b46-542d-937d-baadf4bcdd82.html",
                            "versus": "TRUE",
                            "rowNumber": 2,
                            "$index": 1,
                            "$first": false,
                            "$last": true
                        }
                    ]
                },
                {
                    "race": "Evansdale: Mayor",
                    "candidates": [
                        {
                            "candidate": "Doug Faas",
                            "race": "Evansdale: Mayor",
                            "votes": "368",
                            "totalvotes": "713",
                            "votepercent": "51.61",
                            "precinctsreported": "5",
                            "precincts": "5",
                            "mug": "images/other/faas.jpg",
                            "nobio": "TRUE",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/area-election-roundup-in…n-dunkerton-evansdale-la/article_08bf2605-1b46-542d-937d-baadf4bcdd82.html",
                            "versus": "TRUE",
                            "rowNumber": 3,
                            "$index": 0,
                            "$first": true,
                            "$last": false
                        },
                        {
                            "candidate": "Chad Deutsch",
                            "race": "Evansdale: Mayor",
                            "votes": "345",
                            "totalvotes": "713",
                            "votepercent": "48.39",
                            "precinctsreported": "5",
                            "precincts": "5",
                            "mug": "images/other/deutsch.jpg",
                            "nobio": "TRUE",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/area-election-roundup-in…n-dunkerton-evansdale-la/article_08bf2605-1b46-542d-937d-baadf4bcdd82.html",
                            "versus": "TRUE",
                            "rowNumber": 4,
                            "$index": 1,
                            "$first": false,
                            "$last": true
                        }
                    ]
                },
                {
                    "race": "Hudson: Mayor",
                    "candidates": [
                        {
                            "candidate": "Kevin Launderville",
                            "race": "Hudson: Mayor",
                            "votes": "259",
                            "totalvotes": "453",
                            "votepercent": "57.17",
                            "precinctsreported": "2",
                            "precincts": "2",
                            "mug": "images/other/launderville.jpg",
                            "nobio": "TRUE",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/area-election-roundup-in…n-dunkerton-evansdale-la/article_08bf2605-1b46-542d-937d-baadf4bcdd82.html",
                            "versus": "TRUE",
                            "rowNumber": 5,
                            "$index": 0,
                            "$first": true,
                            "$last": false
                        },
                        {
                            "candidate": "Jeffrey Palmer",
                            "race": "Hudson: Mayor",
                            "votes": "194",
                            "totalvotes": "453",
                            "votepercent": "42.83",
                            "precinctsreported": "2",
                            "precincts": "2",
                            "mug": "images/other/palmer.jpg",
                            "nobio": "TRUE",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/area-election-roundup-in…n-dunkerton-evansdale-la/article_08bf2605-1b46-542d-937d-baadf4bcdd82.html",
                            "versus": "TRUE",
                            "rowNumber": 6,
                            "$index": 1,
                            "$first": false,
                            "$last": true
                        }
                    ]
                },
                {
                    "race": "La Porte City: Mayor",
                    "candidates": [
                        {
                            "candidate": "David Neil",
                            "race": "La Porte City: Mayor",
                            "votes": "352",
                            "totalvotes": "537",
                            "votepercent": "65.55",
                            "precinctsreported": "2",
                            "precincts": "2",
                            "mug": "images/other/neil.jpg",
                            "nobio": "TRUE",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/area-election-roundup-in…n-dunkerton-evansdale-la/article_08bf2605-1b46-542d-937d-baadf4bcdd82.html",
                            "versus": "TRUE",
                            "rowNumber": 7,
                            "$index": 0,
                            "$first": true,
                            "$last": false
                        },
                        {
                            "candidate": "Rick Lubben",
                            "race": "La Porte City: Mayor",
                            "votes": "185",
                            "totalvotes": "537",
                            "votepercent": "34.45",
                            "precinctsreported": "2",
                            "precincts": "2",
                            "mug": "images/other/lubben.jpg",
                            "nobio": "TRUE",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/area-election-roundup-in…n-dunkerton-evansdale-la/article_08bf2605-1b46-542d-937d-baadf4bcdd82.html",
                            "versus": "TRUE",
                            "rowNumber": 8,
                            "$index": 1,
                            "$first": false,
                            "$last": true
                        }
                    ]
                },
                {
                    "race": "Charles City: Mayor",
                    "candidates": [
                        {
                            "candidate": "James Erb",
                            "race": "Charles City: Mayor",
                            "votes": "746",
                            "totalvotes": "1096",
                            "votepercent": "68.07",
                            "precinctsreported": "",
                            "precincts": "",
                            "mug": "images/other/erb.jpg",
                            "nobio": "TRUE",
                            "raceentry": "http://globegazette.com/article_9f85749a-c17e-51a3-b99a-75caf80093f2.html",
                            "versus": "TRUE",
                            "rowNumber": 9,
                            "$index": 0,
                            "$first": true,
                            "$last": false
                        },
                        {
                            "candidate": "Michael Reams",
                            "race": "Charles City: Mayor",
                            "votes": "350",
                            "totalvotes": "1096",
                            "votepercent": "31.93",
                            "precinctsreported": "",
                            "precincts": "",
                            "mug": "images/other/reams.jpg",
                            "nobio": "TRUE",
                            "raceentry": "http://globegazette.com/article_9f85749a-c17e-51a3-b99a-75caf80093f2.html",
                            "versus": "TRUE",
                            "rowNumber": 10,
                            "$index": 1,
                            "$first": false,
                            "$last": true
                        }
                    ]
                },
                {
                    "race": "Issue: Local option sales tax (noncontiguous cities)",
                    "candidates": [
                        {
                            "candidate": "Yes",
                            "race": "Issue: Local option sales tax (noncontiguous cities)",
                            "votes": "257",
                            "totalvotes": "350",
                            "votepercent": "73.43",
                            "precinctsreported": "14",
                            "precincts": "14",
                            "mug": "images/wloo/localoption.jpg",
                            "nobio": "",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/county-voters-ok--year-local-sales-tax-extension/article_917d80d4-6487-5bd4-9585-65fb9111a4eb.html",
                            "versus": "",
                            "rowNumber": 11
                        },
                        {
                            "candidate": "No",
                            "race": "Issue: Local option sales tax (noncontiguous cities)",
                            "votes": "93",
                            "totalvotes": "350",
                            "votepercent": "26.57",
                            "precinctsreported": "14",
                            "precincts": "14",
                            "mug": "images/wloo/localoption.jpg",
                            "nobio": "",
                            "raceentry": "http://wcfcourier.com/news/local/govt-and-politics/county-voters-ok--year-local-sales-tax-extension/article_917d80d4-6487-5bd4-9585-65fb9111a4eb.html",
                            "versus": "",
                            "rowNumber": 12
                        }
                    ]
                }
            ]
        }
    ]
}